dictionaries = ["en_us"]

words = [
  "aacebedo",
  "acebedo",
  "actionid",
  "ajeetdsouza",
  "alexandre",
  "anchore",
  "aquasecurity",
  "atuin",
  "atuinsh",
  "autodiscover",
  "autodiscovered",
  "autoload",
  "biomejs",
  "bindkey",
  "blopker",
  "buildx",
  "captureindex",
  "checkov",
  "chmod",
  "ckv",
  "cli",
  "cocogitto",
  "codeql",
  "commitizen",
  "compdump",
  "compinit",
  "cron",
  "dasel",
  "dependson",
  "devcontaineruser",
  "disableconditions",
  "dockerimage",
  "dprint",
  "editorconfig",
  "eof",
  "eux",
  "eza",
  "filematch",
  "findsubmatch",
  "fpath",
  "fzf",
  "githubrelease",
  "groupby",
  "groupmod",
  "gtrash",
  "hadolint",
  "healthcheck",
  "idursun",
  "initialise",
  "jbc",
  "jbm",
  "jdx",
  "jjui",
  "jujutsu",
  "koalaman",
  "lazygit",
  "linters",
  "lla",
  "lzt",
  "markdownlint",
  "matchpattern",
  "mergify",
  "mise",
  "mkdir",
  "mvdan",
  "neovim",
  "nopasswd",
  "onbuild",
  "opencontainers",
  "passwordless",
  "pipefail",
  "pipx",
  "podman",
  "prek",
  "pullrequest",
  "pypi",
  "replacepattern",
  "ripgrep",
  "rtk",
  "sarif",
  "scmid",
  "scms",
  "sed",
  "sharkdp",
  "shellcheck",
  "shfmt",
  "sourceid",
  "starship",
  "tagfilter",
  "tombi",
  "trimprefix",
  "trivy",
  "umlx",
  "updatecli",
  "usermod",
  "versionfilter",
  "virtualenv",
  "wget",
  "xzf",
  "yamllint",
  "zoxide",
  "zstyle",
]

ignore_paths = [
  "CHANGELOG.md",
  ".vale/**",
  ".git/**",
  ".jj/**",
]
