dictionaries = ["en_us"]

words = [
  "aacebedo",
  "actionid",
  "aquasecurity",
  "autodiscover",
  "autodiscovered",
  "autodiscovery",
  "autoqueue",
  "biomejs",
  "blopker",
  "captureindex",
  "cjs",
  "cli",
  "cocogitto",
  "codebook",
  "commitizen",
  "commitmessage",
  "commitusingapi",
  "boilerplate",
  "cron",
  "devcontainer",
  "devcontaineruser",
  "dprint",
  "dotfiles",
  "editorconfig",
  "findsubmatch",
  "fmt",
  "githubrelease",
  "groupby",
  "gruntwork",
  "hidecredit",
  "jdx",
  "koalaman",
  "linters",
  "matchpattern",
  "mergify",
  "mikefarah",
  "misconfig",
  "mise",
  "mise's",
  "mkdir",
  "mvdan",
  "owenlamont",
  "pep440",
  "pipefail",
  "pipx",
  "prek",
  "pullrequest",
  "pypi",
  "replacepattern",
  "rumdl",
  "rvben",
  "ryl",
  "scmid",
  "scms",
  "scop",
  "sed",
  "shellcheck",
  "shfmt",
  "sourceid",
  "tombi",
  "trimprefix",
  "trivy",
  "updatecli",
  "venv",
  "versionfilter",
  "wasm",
  "yamllint",
  "yamllint's",
  "apparmor",
  "cgroupns",
  "dockerfile",
  "dockerimage",
  "hadolint",
  "nofile",
  "opencontainers",
  "podman",
  "reteps",
  "tagfilter",
  "trivyignore",
  "ulimit",
  "ajeetdsouza",
  "atuin",
  "atuinsh",
  "chmod",
  "eof",
  "eux",
  "eza",
  "fzf",
  "groupmod",
  "gtrash",
  "healthcheck",
  "idursun",
  "jjui",
  "jujutsu",
  "neovim",
  "nopasswd",
  "onbuild",
  "openssh",
  "passwordless",
  "ripgrep",
  "rtk",
  "sharkdp",
  "starship",
  "umlx",
  "usermod",
  "virtualenv",
  "wget",
  "xzf",
  "zoxide",
]

ignore_paths = [
  ".boilerplate-answers.yaml",
  "CHANGELOG.md",
  "cog.toml",
  ".git/**",
  "REUSE.toml",
  "trivy.yaml",
]
