---
branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG.md"
  - "@semantic-release/github"
  - - "@semantic-release/git"
    - message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      assets:
        - "CHANGELOG.md"
  - - "@semantic-release-plus/docker"
    - name:
        registry: ghcr.io
        namespace: aacebedo
        repository: devcontainer-base
        tag: latest
      publishChannelTag: true
