---
ignore: |
  .vale/Google
  .updatecli/manifests/dockerfile.yaml
  .updatecli/manifests/mise.yaml
  .updatecli/manifests/dprint.yaml
  .updatecli/manifests/prek.yaml

rules:
  line-length:
    max: 120
