tag_prefix = "v"
branch_whitelist = ["main"]

post_bump_hooks = [
  "git push",
  "git push origin {{version_tag}}",
  "podman tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:{{version}}",
  "podman push ${IMAGE_NAME}:latest",
  "podman push ${IMAGE_NAME}:{{version}}",
  "cog changelog --at {{version_tag}} --template full_hash > /tmp/cog-release-notes-{{version}}.md",
  "gh release create {{version_tag}} --title {{version_tag}} --notes-file /tmp/cog-release-notes-{{version}}.md",
  "rm -f /tmp/cog-release-notes-{{version}}.md",
]

[commit_types.perf]
bump_patch = true
changelog_title = "Performance Improvements"

[commit_types.revert]
bump_patch = true
changelog_title = "Reverts"

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
owner = "${REPO_OWNER}"
repository = "${REPO_NAME}"
