[settings]
experimental = true

[env]
MISE_GITHUB_TOKEN = { required = true, redact = true }
AUBE_TRUST_POLICY = "off"

[tools]
uv = "0.11.1"
node = "24.18.0"
aube = "1.26.0"
markdownlint-cli2 = "0.23.0"
editorconfig-checker = "3.8.0"
hadolint = "2.14.0"
trivy = "0.72.0"
vale = "3.15.1"
go = "1.26.4"
yamllint = "1.38.0"
# taplo deactivated until their bug is fixed
#taplo = "0.10.0"
prek = "0.4.1"
"npm:@prantlf/jsonlint" = "17.0.1"
"npm:renovate" = "43.268.2"
shfmt = "3.13.0"
shellcheck = "0.11.0"
"pipx:checkov" = "3.3.1"

[tools."npm:semantic-release"]
version = "25.0.2"
aube_args = """\
  @semantic-release/changelog@6.0.3 \
  @semantic-release/exec@7.1.0 \
  @semantic-release/git@10.0.1 \
  @semantic-release-plus/docker@3.1.3
"""

[vars]
repo_owner = '''{{ exec(command="git remote get-url origin | awk -F'[/:]' '{print $(NF-1)}'") | trim }}'''
repo_name = '''{{ exec(command="git remote get-url origin | xargs basename -s .git") | trim }}'''
repo_url = "https://github.com/{{vars.repo_owner}}/{{vars.repo_name}}"
docker_tag = "ghcr.io/{{vars.repo_owner}}/{{vars.repo_name}}:latest"

[bootstrap.packages]
"apt:passwd" = "latest"
"apt:bash" = "latest"
"apt:podman" = "latest"
"apt:podman-docker" = "latest"
"apt:fuse-overlayfs" = "latest"
"apt:iptables" = "latest"
"apt:build-essential" = "latest"
