[settings]
experimental = true

[env]
MISE_GITHUB_TOKEN = { required = true, redact = true }

[tools]
uv = "0.12.1"
node = "24.19.0"
markdownlint-cli2 = "0.23.0"
editorconfig-checker = "3.11.1"
hadolint = "2.15.1"
trivy = "0.73.0"
vale = "3.17.0"
yamllint = "1.38.0"
# taplo deactivated until their bug is fixed
# taplo = "0.10.0"
prek = "0.4.1"
shfmt = "3.13.0"
shellcheck = "0.11.0"
dprint = "0.55.2"
"pipx:checkov" = "3.3.1"
cocogitto = "7.0.0"
gh = "2.97.0"

[tools."npm:renovate"]
version = "44.17.1"
trust_policy_excludes = ["@yarnpkg/libzip"]

[vars]
repo_owner = '''{{ exec(command="git remote get-url origin | awk -F'[/:]' '{print $(NF-1)}'") | trim }}'''
repo_name = '''{{ exec(command="git remote get-url origin | xargs basename -s .git") | trim }}'''
repo_url = "https://github.com/{{vars.repo_owner}}/{{vars.repo_name}}"
image_name = "ghcr.io/{{vars.repo_owner}}/{{vars.repo_name}}"
commit_sha = '''{{ exec(command="git rev-parse HEAD") | trim }}'''

[bootstrap.packages]
"apt:bash" = "latest"
"apt:podman" = "latest"
"apt:fuse-overlayfs" = "latest"
"apt:iptables" = "latest"
"apt:build-essential" = "latest"
