---
name: PR

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  pr-checks:
    runs-on: ubuntu-26.04
    permissions:
      contents: read
      packages: read
    steps:
      - name: Setup
        uses: ./.github/actions/setup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          actor: ${{ github.actor }}
          repository: ${{ github.repository }}
      - name: Lint
        run: |
          mise lint
      - name: Test
        run: |
          mise test
      - name: Run security scan
        run: |
          mise security-scan
