---
name: Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    uses: aacebedo/boilerplate-templates/.github/workflows/reusable-release.yaml@v0.3.3
    secrets: inherit
    permissions:
      contents: write
      packages: write
