---
name: Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    runs-on: ubuntu-26.04
    permissions:
      contents: write
      packages: write
      actions: read
      security-events: write
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0
          fetch-tags: true
      - name: Setup
        uses: ./.github/actions/setup
        with:
          actor: ${{ github.actor }}
          repository: ${{ github.repository }}
          token: ${{ steps.generate-token.outputs.token }}
      - name: Perform release
        id: release
        run: |
          mise release
          echo "sarif=/tmp/trivy-results.sarif" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Anchore Scan SARIF Report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${{ steps.release.outputs.sarif }}
